<a href="https://colab.research.google.com/github/R1ng1/MDSC-201-Statistical-Methods-Using-R/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **R Basics**

##**1. Vectors**

In [1]:
v <- c(5, 15, 25, 35, 45)
print(v)
print(length(v))
print(class(v))


[1]  5 15 25 35 45
[1] 5
[1] "numeric"


## **2. Lists**

In [3]:

my_list <- list("Data Science", 42.42, FALSE, c("A", "B", "C"))
print(my_list)
print(my_list[[3]])  # Accesses the third element.

[[1]]
[1] "Data Science"

[[2]]
[1] 42.42

[[3]]
[1] FALSE

[[4]]
[1] "A" "B" "C"

[1] FALSE


## **3. Matrices**

In [2]:
matrix_1 <- matrix(10:18, nrow = 3, ncol = 3)
print(matrix_1)
print(matrix_1[3, 1])  # Access element in the 3rd row, 1st column.


     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18
[1] 12


##**4. Arrays**

In [4]:
array_1 <- array(1:18, dim = c(3, 3, 2))
print(array_1)
print(array_1[2, 3, 2])  # Access element at 2nd row, 3rd column, 2nd matrix.

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18

[1] 17


## **5. Factors**

In [5]:
factor_1 <- factor(c("High", "Low", "High", "Medium", "Low"))
print(factor_1)
print(levels(factor_1))


[1] High   Low    High   Medium Low   
Levels: High Low Medium
[1] "High"   "Low"    "Medium"


##**6. Data Frames**

In [6]:
df <- data.frame(Name = c("David", "Eve", "Frank"),
                 Age = c(22, 28, 34),
                 Marks = c(78, 85, 92))
print(df)
print(df$Marks)

   Name Age Marks
1 David  22    78
2   Eve  28    85
3 Frank  34    92
[1] 78 85 92


##**7. ls Function**

In [7]:
var1 <- "Hello"
var2 <- 123
my_var <- TRUE
print(ls(pattern = "var"))

[1] "my_var" "var1"   "var2"  


## **8. Assigning Variable**

In [8]:
a <- 25
b = "Welcome"
TRUE -> c
print(a)
print(b)
print(c)
cat("a is", a, "\n")
cat("b is", b, "\n")
cat("c is", c, "\n")


[1] 25
[1] "Welcome"
[1] TRUE
a is 25 
b is Welcome 
c is TRUE 


## **9. Finding Variables**

In [10]:
varA <- c(4, 5, 6)
varB <- "Statistics"
example_var <- 50
print(ls())
print(ls(pattern = "var"))

 [1] "a"           "array_1"     "b"           "c"           "df"         
 [6] "example_var" "factor_1"    "matrix_1"    "my_list"     "my_var"     
[11] "v"           "var1"        "var2"        "varA"        "varB"       
[1] "example_var" "my_var"      "var1"        "var2"        "varA"       
[6] "varB"       


## **10. Deleting Variables**

In [11]:
a <- 100
b <- 200
c <- 300
print("Variables before deletion:")
print(ls())
rm(b)
print("Variables after deleting 'b':")
print(ls())
rm(list = ls())
print("Variables after deleting all:")
print(ls())


[1] "Variables before deletion:"
 [1] "a"           "array_1"     "b"           "c"           "df"         
 [6] "example_var" "factor_1"    "matrix_1"    "my_list"     "my_var"     
[11] "v"           "var1"        "var2"        "varA"        "varB"       
[1] "Variables after deleting 'b':"
 [1] "a"           "array_1"     "c"           "df"          "example_var"
 [6] "factor_1"    "matrix_1"    "my_list"     "my_var"      "v"          
[11] "var1"        "var2"        "varA"        "varB"       
[1] "Variables after deleting all:"
character(0)


## **11. Adding Two Vectors**

In [12]:
vec1 <- c(10, 20, 30)
vec2 <- c(1, 2, 3)
result <- vec1 + vec2
print(result)


[1] 11 22 33


##**12. Subtracting Two Vectors**

In [13]:
vec1 <- c(50, 60, 70)
vec2 <- c(10, 20, 30)
result <- vec1 - vec2
print(result)

[1] 40 40 40


##**13. Division of Vectors**

In [14]:
vec1 <- c(100, 200, 300)
vec2 <- c(2, 4, 5)
result <- vec1 / vec2
print(result)

[1] 50 50 60


##**14. Colon Operator**

In [15]:
sequence <- 20:30
print(sequence)


 [1] 20 21 22 23 24 25 26 27 28 29 30


##**15. %in% Operator**

In [16]:
vec <- c("cat", "dog", "rabbit")
print("dog" %in% vec)
print("lion" %in% vec)

[1] TRUE
[1] FALSE


##**16. Matrix Multiplication**

In [17]:
matrix1 <- matrix(2:7, nrow = 2, ncol = 3)
transpose <- t(matrix1)
result <- matrix1 %*% transpose
print(result)


     [,1] [,2]
[1,]   56   68
[2,]   68   83


##**17. if Statement**

In [18]:
y <- 8
if (y < 10) {
  print("y is less than 10")
}

[1] "y is less than 10"


##**18. if...else if...else Statement**

In [19]:
z <- 20
if (z < 15) {
  print("z is less than 15")
} else if (z == 20) {
  print("z is equal to 20")
} else {
  print("z is greater than 20")
}


[1] "z is equal to 20"


#19. While Loop

In [20]:
x <- 2
while (x <= 8) {
  print(x)
  x <- x + 2
}


[1] 2
[1] 4
[1] 6
[1] 8


##**20. Repeat Loop**

In [21]:
x <- 1
repeat {
  print(x)
  x <- x + 1
  if (x > 4) {
    break
  }
}

[1] 1
[1] 2
[1] 3
[1] 4


##**21. For Loop**

In [22]:
for (i in 6:10) {
  print(i)
}


[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


##**22. Break Statement**

In [23]:
for (i in 1:8) {
  if (i == 5) {
    break
  }
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4


##**23. Next Statement**

In [24]:
for (i in 1:5) {
  if (i == 2) {
    next
  }
  print(i)
}

[1] 1
[1] 3
[1] 4
[1] 5
