<a href="https://colab.research.google.com/github/R1ng1/MDSC-201-Statistical-Methods-Using-R/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **R Functions**

# **Fundamental operations and concepts in R programming**

## **Creating a vector**

In [172]:
v <- c(10, 20, 30, 40, 50)
print(v)


[1] 10 20 30 40 50


## **Generating sequences**

In [173]:
seq1 <- seq(1, 10, by=2)
print(seq1)

[1] 1 3 5 7 9


## **Repeating elements**

In [174]:
rep1 <- rep(c(1, 2, 3), times=3)
print(rep1)

[1] 1 2 3 1 2 3 1 2 3


## **Getting vector length**

In [175]:
print(length(v))

[1] 5


## **Sorting values**

In [176]:
sorted_v <- sort(v, decreasing = TRUE)
print(sorted_v)

[1] 50 40 30 20 10


## **Getting ordering index**

In [177]:
idx <- order(v)
print(idx)

[1] 1 2 3 4 5


## **Reversing elements**

In [178]:
rev_v <- rev(v)
print(rev_v)

[1] 50 40 30 20 10


## **Finding unique values**

In [179]:
unique_v <- unique(c(1, 2, 2, 3, 3, 3, 4))
print(unique_v)

[1] 1 2 3 4


## **Frequency table**

In [180]:
print(table(c("A", "B", "A", "C", "B", "A")))



A B C 
3 2 1 


## **Finding indices of matching values**


In [181]:
match_idx <- match(c(20, 40), v)
print(match_idx)

[1] 2 4


## **Checking if value exists**

In [182]:
exists <- 30 %in% v
print(exists)


[1] TRUE


## **Finding index of elements satisfying a condition**

In [183]:
idx_condition <- which(v > 25)
print(idx_condition)

[1] 3 4 5


## **Checking if any value is TRUE**


In [184]:
print(any(v > 45))

[1] TRUE


## **Checking if all values are TRUE**

In [185]:
print(all(v > 5))

[1] TRUE


## **Checking for missing values**

In [186]:
v_with_na <- c(10, 20, NA, 40)
print(is.na(v_with_na))

[1] FALSE FALSE  TRUE FALSE


## **Removing NA values**

In [187]:
clean_v <- na.omit(v_with_na)
print(clean_v)

[1] 10 20 40
attr(,"na.action")
[1] 3
attr(,"class")
[1] "omit"


## **Replacing values**

In [188]:
replaced_v <- replace(v, v == 20, 100)
print(replaced_v)

[1]  10 100  30  40  50


## **Concatenating strings**

In [189]:
str_concat <- paste("Hello", "World", sep=" ")
print(str_concat)

[1] "Hello World"


## **Concatenating without spaces**

In [190]:
print(paste0("Hello", "World"))


[1] "HelloWorld"


## **Convert to uppercase**

In [191]:
print(toupper("hello"))


[1] "HELLO"


## **Convert to lowercase**

In [192]:
print(tolower("HELLO"))

[1] "hello"


## **Extract substring**

In [193]:
print(substr("HelloWorld", 1, 5))

[1] "Hello"


## **Pattern matching**

In [194]:
matches <- grep("e", c("apple", "banana", "cherry"), value=TRUE)
print(matches)


[1] "apple"  "cherry"


## **Replace pattern**

In [195]:
print(gsub("a", "@", "banana"))

[1] "b@n@n@"


## **Split strings**

In [196]:
splitted <- strsplit("a,b,c", ",")
print(splitted)

[[1]]
[1] "a" "b" "c"



## **Convert to numeric**

In [197]:
print(as.numeric("123"))

[1] 123


## **Convert to character**

In [198]:
print(as.character(123))

[1] "123"


## **Convert to factor**

In [199]:
factors <- as.factor(c("Low", "Medium", "High"))
print(factors)

[1] Low    Medium High  
Levels: High Low Medium


## **Convert to date**


In [200]:
date_val <- as.Date("2024-02-05")
print(date_val)

[1] "2024-02-05"


## **Get current date**

In [201]:
print(Sys.Date())

[1] "2025-03-28"


## **Array**

In [202]:
nums <- c(10, 20, 30, 40)

## **Sum**

In [203]:
print(sum(nums))

[1] 100


## **Product**

In [204]:
print(prod(nums))

[1] 240000


## **Cumulative sum**

In [205]:
print(cumsum(nums))


[1]  10  30  60 100


## **Cumulative product**

In [206]:
print(cumprod(nums))

[1]     10    200   6000 240000


## **Mean**

In [207]:
print(mean(nums))

[1] 25


## **Median**

In [208]:
print(median(nums))


[1] 25


## **Minimum**

In [209]:
print(min(nums))

[1] 10


# Maximum

In [210]:
print(max(nums))

[1] 40


## **Range**

In [211]:
print(range(nums))

[1] 10 40


## **Variance**

In [212]:
print(var(nums))


[1] 166.6667


## **Standard deviation**

In [213]:
print(sd(nums))

[1] 12.90994


## **Compute quantiles**

In [214]:
print(quantile(nums, probs = c(0.25, 0.5, 0.75)))


 25%  50%  75% 
17.5 25.0 32.5 


## **Round values**

In [215]:
print(round(3.14159, 2))

[1] 3.14


## **Ceiling**

In [216]:
print(ceiling(3.6))

[1] 4


## **Floor**

In [217]:
print(floor(3.6))

[1] 3


## **Absolute value**


In [218]:
print(abs(-10))


[1] 10


## **Square root**

In [219]:
print(sqrt(25))

[1] 5


## **Natural logarithm**

In [220]:
print(log(10))

[1] 2.302585


## **Exponential function**

In [221]:
print(exp(2))


[1] 7.389056


## **Factorial**

In [222]:
print(factorial(5))

[1] 120


## **Binomial coefficient**

In [223]:
print(choose(5, 2))

[1] 10


## **Trigonometric functions**

In [224]:
print(sin(pi/2))
print(cos(0))
print(tan(pi/4))

[1] 1
[1] 1
[1] 1


## **Correlation coefficient**

In [225]:
x <- c(1, 2, 3, 4, 5)
y <- c(2, 4, 6, 8, 10)
print(cor(x, y))

[1] 1


## **Covariance**

In [226]:
print(cov(x, y))

[1] 5


## **Creating data structures**

In [227]:
df <- data.frame(Name=c("A", "B", "C"), Score=c(90, 85, 88))
print(df)

lst <- list(Name="John", Age=25)
print(lst)

mat <- matrix(1:9, nrow=3)
print(mat)

arr <- array(1:12, dim=c(2,2,3))
print(arr)

  Name Score
1    A    90
2    B    85
3    C    88
$Name
[1] "John"

$Age
[1] 25

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]   10   12



## **Transpose matrix**

In [228]:
print(t(mat))

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


## **Row and Column binding**

In [229]:
mat1 <- matrix(1:6, nrow=2)
print(rbind(mat1, c(7,8,9)))
print(cbind(mat1, c(10,11)))


     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
[3,]    7    8    9
     [,1] [,2] [,3] [,4]
[1,]    1    3    5   10
[2,]    2    4    6   11


## **Get dimensions**

In [230]:
print(dim(df))

[1] 3 2


## **Number of rows & columns**

In [231]:
print(nrow(df))
print(ncol(df))


[1] 3
[1] 2


## **Get and set names**

In [232]:
print(names(df))

[1] "Name"  "Score"


## **Subset data**

In [233]:
subset_df <- subset(df, Score > 85)
print(subset_df)

  Name Score
1    A    90
3    C    88


## **Merge data frames**

In [234]:
df2 <- data.frame(Name=c("A", "B"), Age=c(20, 21))
merged_df <- merge(df, df2, by="Name")
print(merged_df)


  Name Score Age
1    A    90  20
2    B    85  21


## **Apply functions**

In [235]:
print(apply(mat, 1, sum))

[1] 12 15 18


## **Aggregation**

In [236]:
print(aggregate(Score ~ Name, data=df, FUN=mean))


  Name Score
1    A    90
2    B    85
3    C    88


## **Conditional execution**

In [237]:
x <- 10
if (x > 5) print("Greater than 5") else print("Not greater")


[1] "Greater than 5"


## **Loop over sequence**

In [238]:
for (i in 1:5) {
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


## **While loop**


In [239]:
i <- 1
while (i <= 5) {
  print(i)
  i <- i + 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


## **Repeat loop with break**

In [240]:
j <- 1
repeat {
  print(j)
  if (j == 5) break
  j <- j + 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


## **Define and call function**

In [241]:
add_nums <- function(a, b) {
  return(a + b)
}
print(add_nums(5, 10))


[1] 15


## **Get and set working directory**

In [242]:
print(getwd())  # Print the current working directory

[1] "/home/user/R_programming"


## **Correct way to change directory (ensure the path exists)**

In [243]:

# Verify the directory exists and create it if necessary
# Note: The directory might already exist, so check before creating.
if (!dir.exists("/home/user/R_programming")) {
    dir.create("/home/user/R_programming", recursive = TRUE)
}

# Change to the directory using the absolute path
setwd("/home/user/R_programming")  # Use absolute path

# Verify if the working directory changed successfully
print(getwd())

[1] "/home/user/R_programming"


## **Verify if the working directory changed successfully**

In [244]:
print(getwd())

[1] "/home/user/R_programming"


## **List files in the working directory**

In [245]:
print(list.files())


[1] "data.rds"   "output.csv"


## **Check if the data file exists before reading**

In [246]:
if (file.exists("data.csv")) {
  df <- read.csv("data.csv")  # Read CSV file
  print(head(df))  # Display first few rows of the data
} else {
  print("Error: data.csv not found in the working directory.")
}


[1] "Error: data.csv not found in the working directory."


## **Write data to a CSV file safely**

In [247]:
df_sample <- data.frame(Name=c("Alice", "Bob", "Charlie"), Score=c(90, 85, 88))
write.csv(df_sample, "output.csv", row.names=FALSE)  # Avoid writing row numbers


## **Check if the RDS file exists before reading**

In [248]:
if (file.exists("data.rds")) {
  df_loaded <- readRDS("data.rds")  # Read R object
  print(df_loaded)
} else {
  print("Error: data.rds not found. Saving new RDS file.")
  saveRDS(df_sample, "data.rds")  # Save data as RDS for future use
}


     Name Score
1   Alice    90
2     Bob    85
3 Charlie    88


## **Grades**

In [249]:
grades <- factor(c("A", "B", "A", "C"))
print(levels(grades))

[1] "A" "B" "C"


## **Reorder levels**

In [250]:
relevel(grades, ref="B")

[1] A B A C
Levels: B A C

## Convert numeric to factor

In [251]:
grouped <- cut(c(10, 20, 30), breaks=3)
print(grouped)


[1] (9.98,16.7] (16.7,23.3] (23.3,30]  
Levels: (9.98,16.7] (16.7,23.3] (23.3,30]


## **Convert to date**

In [252]:
date1 <- as.Date("2025-02-05")
print(date1)

[1] "2025-02-05"


## **Convert to POSIX format**

In [253]:
datetime <- as.POSIXct("2025-02-05 10:30:00")
print(datetime)

[1] "2025-02-05 10:30:00 UTC"


## **Compute time difference**

In [254]:
diff <- difftime(Sys.Date(), as.Date("2025-01-01"), units="days")
print(diff)

Time difference of 86 days


## **Format date**

In [255]:
print(format(Sys.Date(), "%d-%b-%Y"))

[1] "28-Mar-2025"


## **List objects**


In [256]:
print(ls())

 [1] "add_nums"      "arr"           "clean_v"       "date_val"     
 [5] "date1"         "datetime"      "df"            "df_loaded"    
 [9] "df_sample"     "df2"           "diff"          "exists"       
[13] "factors"       "grades"        "grouped"       "i"            
[17] "idx"           "idx_condition" "j"             "lst"          
[21] "mat"           "mat1"          "match_idx"     "matches"      
[25] "merged_df"     "nums"          "rep1"          "replaced_v"   
[29] "rev_v"         "seq1"          "sorted_v"      "splitted"     
[33] "str_concat"    "subset_df"     "unique_v"      "v"            
[37] "v_with_na"     "x"             "y"            


## **Remove object**

In [257]:
rm(x)

## **Garbage collection**

In [258]:
gc()

used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  693323 37.1 1439690    76.9 1439690  76.9
Vcells 1308806 10.0 8388608    64.0 2205768  16.9

## **Debugging**

In [259]:
debug(add_nums)
print(add_nums(5, 10))
undebug(add_nums)


debugging in: add_nums(5, 10)
debug: {
    return(a + b)
}
debug: return(a + b)
exiting from: add_nums(5, 10)
[1] 15


## **Print output**

In [260]:
print("Hello, World!")
cat("Hello, World!\n")

[1] "Hello, World!"
Hello, World!
